### ISSUE TITLE
events.js:187  throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by kalyanitcse05** [garygrossgarten/github-action-scp#13]
Hi,
I am using garygrossgarten/github-action-scp@release, even though it copies the files, i am getting errors, which makes build looks failed
✅ scp Action finished.
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/dist/index.js:9794:10)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}

Can you let me know if i am missing anything

**Comment by djavier** [comment]
@kalyanitcse05 Do you finally get this working? If so, can you point me in the right direction.....I happen to be blocked by this very same error.

@garygrossgarten any suggestion, might this be related with the node version used to compile the package?

````
✔ successfully copied API\Properties\PublishProfiles\Deploy.pubxml.
The copy of directory ./API was successful.
✅ scp Action finished.
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (D:\a\_actions\garygrossgarten\github-action-scp\v0.6.0\dist\index.js:9794:10)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}`

```

YML Config:
```
       uses: garygrossgarten/github-action-scp@v0.6.0
          with:
          local: ./API
          remote: D:\Sites\testCI
          host: ${{secrets.ODD_TESTSERVER}}
          username: ${{secrets.ODD_DEPLOY_USERNAME}}
          port: 22
          password: ${{secrets.ODD_DEPLOY_PASSWORD}}
          tryKeyboard: ${{secrets.ODD_DEPLOY_PASSWORD}}
```
