### ISSUE TITLE
Timed out while waiting for handshake

### ISSUE THREAD

**Issue by pasudo123** [garygrossgarten/github-action-scp#14]
Thank you for making useful open source.
No wonder i am currently using `garygrossgarten/github-action-scp@release`.

my service structure now is that the web server of NAS storage at home is running and the jar file built through scp protocol.

{github action} <- SCP -> {home : NAS}

as the currently secrets setting, the host is set to ip and the username & password of the account to nas are also registered. 
and the port is currently in port forwarding state, so it is set to a number other than 22.

here are my yml file setting and error messages. what is the problem..?

```yml
      - name: Copy file via ssh password
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local: ./movie-masterpiece-club-web/build/libs/sample.txt
          remote: /volume1/docker/deploy/www/masterpiece-web/ 
```

```
⚠️ The GitHub Action couldn't connect to ***. Error: Timed out while waiting for handshake
    at Timeout._onTimeout (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/dist/index.js:10182:19)
##[error]Timed out while waiting for handshake
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  level: 'client-timeout'
}
Starting scp Action: ./movie-masterpiece-club-web/build/libs/sample.txt to /volume1/docker/deploy/www/masterpiece-web/
⚠️ An error happened:(. Not connected Error: Not connected
```
