### ISSUE TITLE
There is a success info but nothing on the remote folder.

### ISSUE THREAD

**Issue by shuiRong** [garygrossgarten/github-action-scp#17]
Github Action Log is [here](https://github.com/MakeGolangGreat/MastodonArchiveBot/runs/1078348131?check_suite_focus=true). and you can see this:`✅ scp Action finished.`

But I don't see any file in the remote server. It's weird.

[here](https://github.com/MakeGolangGreat/MastodonArchiveBot/blob/f00c237cdc6c353a57b87baa1778a94634176254/.github/workflows/go.yml#L27) is my config.

```
            - name: deploy
              uses: garygrossgarten/github-action-scp@release
              with:
                local: deploy
                remote: /root/mastodon/
                host: ${{ secrets.SERVER_IP }}
                username: root
                password: ${{secrets.SERVER_PASSWORD}}
```
