### ISSUE TITLE
localFile does not exist with wildcard

### ISSUE THREAD

**Issue by poespas** [garygrossgarten/github-action-scp#19]
Hi,

I'm getting an error thrown when I try to transfer a bunch of files containing a wildcard as localFile.

Example:
```
- name: Copy dist CSS to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist/css/*.css
          remote: /data/html/css/
```

Error `An error happened:(. localFile does not exist at dist/css/app*.css AssertionError [ERR_ASSERTION]: localFile does not exist at dist/css/app*.css`
