### ISSUE TITLE
localFile does not exist

### ISSUE THREAD

**Issue by Michael21011** [garygrossgarten/github-action-scp#2]
Hi all,

I am receiving error when try to use this action

```
Run garygrossgarten/github-action-scp@release
  with:
    local: dotnetcorewebapp/AzsValidator.dll
    remote: azsvalidator
    host: ***
    username: ***
    password: ***
    port: 22
    concurrency: 1
    recursive: true
    verbose: true
  env:
    DOTNET_ROOT: /opt/hostedtoolcache/dncs/2.2.108/x64
Establishing a SSH connection to ***.
🤝 Connected to ***.
Starting scp Action: dotnetcorewebapp/AzsValidator.dll to azsvalidator
⚠️ An error happened:(. localFile does not exist at dotnetcorewebapp/AzsValidator.dll AssertionError [ERR_ASSERTION]: localFile does not exist at dotnetcorewebapp/AzsValidator.dll
    at /home/runner/work/_actions/garygrossgarten/github-action-scp/release/node_modules/node-ssh/lib/index.js:236:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/node_modules/node-ssh/lib/index.js:21:103)
    at _next (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/node_modules/node-ssh/lib/index.js:23:194)
 1: 0x98edf0 node::Abort() [/home/runner/runners/2.161.0/externals/node12/bin/node]
 2: 0x9ff1b9  [/home/runner/runners/2.161.0/externals/node12/bin/node]
 3: 0xb9cae6  [/home/runner/runners/2.161.0/externals/node12/bin/node]
 4: 0xb9e9f9 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/runner/runners/2.161.0/externals/node12/bin/node]
 5: 0x1a93942  [/home/runner/runners/2.161.0/externals/node12/bin/node]
```

Is it my error with configuration or action is broken?

**Comment by ngrealish** [comment]
I'm getting the same error, but I just don't know where Github is looking for the root.

**Comment by Michael21011** [comment]
Hi @ngrealish 
I solved this issue.
You ar right, there was an issue with local path, full path should be used, for my project it looks like `/home/runner/work/ValidateAzs/ValidateAzs/AzsValidator/dotnetcorewebapp/`
I found this path in output of my publish step:
![image](https://user-images.githubusercontent.com/9266780/70117035-7057ac00-1675-11ea-922b-a6ef8b7e7f63.png)
Another important thing: this should by as step in one job with publish step, not separate job, please see below full code of action:
```
name: .NET Core

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o dotnetcorewebapp  
    - name: copy file via ssh password
      uses: garygrossgarten/github-action-scp@release
      with:
          local: /home/runner/work/ValidateAzs/ValidateAzs/AzsValidator/dotnetcorewebapp/
          remote: azsvalidator
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
```
