### ISSUE TITLE
Environmental variables are not supported

### ISSUE THREAD

**Issue by edi33416** [garygrossgarten/github-action-scp#26]
Cheers,

I'm trying to use expand a variable for the local source directory, like so:
```
      - name: Publish labs to elf
        uses: garygrossgarten/github-action-scp@release
        with:
          local: "$LOCAL_LAB_PUBLISH_DIR"
          remote: "$LAB_PUBLISH_DIR"
```

but I'm getting the following error
```
Starting scp Action: $LOCAL_LAB_PUBLISH_DIR to $LAB_PUBLISH_DIR
⚠️ An error happened:(. localFile does not exist at $LOCAL_LAB_PUBLISH_DIR AssertionError [ERR_ASSERTION]: localFile does not exist at $LOCAL_LAB_PUBLISH_DIR
    at NodeSSH.putFile (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/dist/index.js:10343:25)
```

Could we get env support?
