### ISSUE TITLE
Dotfiles being copied all the time

### ISSUE THREAD

**Issue by tiliv** [garygrossgarten/github-action-scp#28]
Hi!

I've been using this action to copy repository code to a remote server, and I noticed that whether I set `dotfiles: false` or leave it out (because default is `false`), the scp is copying folders and files that start with `.`.  My workaround is to remove the files in question before using the scp action.

Here is the step I'm using to perform the transfer:
```yaml
      - name: Copy sources to Instance
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          host: ${{ steps.set-ssh-info.outputs.host }}
          port: ${{ steps.set-ssh-info.outputs.port }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          local: my-dir
          remote: my-dir
```
