### ISSUE TITLE
unsupported key format

### ISSUE THREAD

**Issue by razagill** [garygrossgarten/github-action-scp#3]
Hi,
I'm trying to get this action working with the `privateKey` option. But I'm running in to the error where it says `Unsupported key format`.

I've tried downgrading my key as mentioned in this issue https://github.com/steelbrain/node-ssh/issues/149 of the `node-ssh` module but still the problem remains.

Here is the workflow part:
```
- name: Push Release To Deploy (Staging)
      uses: garygrossgarten/github-action-scp@release
      with:
        local: "_build/"
        remote: "/home/user/ribbit/build"
        host: ${{ secrets.STAGING_HOST }}
        username: "ribbit"
        privateKey: $${{ secrets.STAGING_HOST_KEY }}
```
