### ISSUE TITLE
Using RSA Private Key to Deploy in EC2

### ISSUE THREAD

**Issue by lhcavalcanti** [garygrossgarten/github-action-scp#30]
Hello,

I'm trying to deploy the build of my app through the SCP directly in my EC2 instance, but I'm getting error in reading the key file (it is private RSA key from AWS).

Error:
```
⚠️ The GitHub Action couldn't connect to *** Error: Cannot parse privateKey: Unsupported key format
    at Client.module.exports.597.Client.connect (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/dist/index.js:11745:13)
Error: Cannot parse privateKey: Unsupported key format
    at /home/runner/work/_actions/garygrossgarten/github-action-scp/release/dist/index.js:10148:24
    at new Promise (<anonymous>)
    at NodeSSH.connect (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/dist/index.js:10128:15)
    at /home/runner/work/_actions/garygrossgarten/github-action-scp/release/dist/index.js:11364:23
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/garygrossgarten/github-action-scp/release/dist/index.js:11282:71
    at new Promise (<anonymous>)
    at module.exports.526.__awaiter (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/dist/index.js:11278:12)
    at connect (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/dist/index.js:11347:12)
Starting scp Action: m3s-app.zip to /home/ubuntu/
⚠️ An error happened:(. Not connected Error: Not connected
Error: Not connected
```

Workflow config:
- name: Transfer Build
        uses: garygrossgarten/github-action-scp@release
        with:
          local: "app.zip"
          remote: "/home/ubuntu/"
          host: ${{ secrets.AWS_HOST }}
          username: "ubuntu"
          privateKey: ${{ secrets.AWS_PEM }}
          
Am I doing something wrong? Or it does not support this type of key?

Thanks!

**Comment by MaLIE2018** [comment]
I have the same problem, that it is not clear to me, why my key is not accepted.

**Comment by Dud3core-webdev** [comment]
I have the same problem trying to connect to a Digital Ocean Droplet. 

The key format is 

```
-----BEGIN OPENSSH PRIVATE KEY-----
{{key data}}
-----END OPENSSH PRIVATE KEY-----
```

my deploy script looks like this 

```yml
name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Release Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --verbosity normal
    - name: Start Deploy
      uses: garygrossgarten/github-action-scp@release
      with: 
        local: /home/runner/work/MfWebDevApiCore/MfWebDevApiCore/MfWebDevServiceNew/bin/Release
        remote: var/www/MfWebDevServices
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        privateKey: ${{ secrets.SSH_KEY }}
        rmRemote: true
        dotfiles: true
```

**Comment by matheusfrancisco** [comment]
@Dud3core-webdev I have had this same problem, how did u solve this?

**Comment by Dud3core-webdev** [comment]
@matheusfrancisco I added my SSH passphrase with the call: 

```
- name: Deploy to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          source: path/bin/Release
          target: var/www/path
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSWORD }} <-- This was missing
          rm: true
```
It worked every time after that
