### ISSUE TITLE
An error happened:(. Failure Error: Failure at SFTPStream.module.exports.157.SFTPStream._transfor

### ISSUE THREAD

**Issue by agitnaeta** [garygrossgarten/github-action-scp#32]
Establishing a SSH connection to ***.
(node:2349) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
🤝 Connected to ***.
Starting scp Action: website.tar.gz to /home/***/portal
⚠️ An error happened:(. Failure Error: Failure
    at SFTPStream.module.exports.157.SFTPStream._transform (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/dist/index.js:1277:27)
Error: Failure
    at SFTPStream.Transform._read (_stream_transform.js:189:10)
    at SFTPStream.module.exports.157.SFTPStream._read (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/dist/index.js:1048:15)
    at SFTPStream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at SFTPStream.Writable.write (_stream_writable.js:305:11)
    at Channel.ondata (_stream_readable.js:727:22)
    at Channel.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
✅ scp Action finished.

**Comment by julled** [comment]
I am getting exactly the same error. Would love to get it fixed.

```
jobs:
  build:
    runs-on:  ubuntu-18.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: README.md 
          remote: ~
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}

```
