### ISSUE TITLE
'ETIMEDOUT' for a file sized 388K

### ISSUE THREAD

**Issue by okunamayanad** [garygrossgarten/github-action-scp#45]
I initially tried uploading an astro build, although it passed 2 minute so I thought something was off,
tried zipping it but it passed 2 minute too but for this time I went for it to crash.
And it did at 17 minutes and 23 seconds.
![image](https://github.com/garygrossgarten/github-action-scp/assets/108594296/5033861f-3756-4013-b094-35dfba582f19)
After this, I tried uploading a smaller file, that just had hello world in it, thinking that if this is something I caused, this will fail too.
It actually worked fine.
![image](https://github.com/garygrossgarten/github-action-scp/assets/108594296/f697a4f3-7161-49cb-8ffe-8e8d21c58991)
What should I do?
The problematic file:
```
  publish:
    needs: clear-web
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Check Node.js version
        run: node --version

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist.zip dist

      - name: Check Archive
        run: ls -l dist.zip

      - name: Check Archive Size
        run: du -sh dist.zip

      - name: Upload
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist.zip
          remote: /tmp/c+/dist.zip
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
``` 
The working file:
```
publish:
    needs: clear-web
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Check Node.js version
        run: node --version

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist.zip dist

      - name: Check Archive
        run: ls -l dist.zip

      - name: Check Archive Size
        run: du -sh dist.zip

      - name: Create a small file for testing purposes
        run: echo "Hello World" > test.txt

      - name: Check Test File
        run: ls -l test.txt

      - name: Check Test File Size
        run: du -sh test.txt

      - name: Upload Test File
        uses: garygrossgarten/github-action-scp@release
        with:
          local: test.txt # testing 
          remote: /tmp/c+/test.txt # testing
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
```
