### ISSUE TITLE
Upload compressed files doesn't work

### ISSUE THREAD

**Issue by sact1909** [garygrossgarten/github-action-scp#50]
I'm trying to upload a .tar file, but when the action connects to the server it uploads the tar file  with a dot in front of the name and don't remove the existing files just paste the tar file with a wrong name and delay a lot after that, just pass as it worked but not, is uploading the file with a wrong nade and never delete the existing files

Example
Correct: "Contabo.tar"
Action: ".Contabo.tar" 

my yml file 

````
name: Deploy to Contabo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NUGET_URL: "https://nuget.devexpress.com/api"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Ensure GitHub NuGet Source
      run: |
        dotnet nuget add source ${{ env.NUGET_URL }} \
        -n DevExpressFeed \
        -u DevExpress \
        -p ${{ secrets.DEVEXPRESS_NUGET_KEY }} \
        --store-password-in-clear-text
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: dotnet publish
      run: dotnet publish -c Release --no-restore -o ./publish 

    - name: Creating Artifact
      run: |
           mkdir ./Zipfiles
           cd publish
           tar cvf ../Contabo.tar *
           cd ..
           mv Contabo.tar ./Zipfiles 

    #- uses: actions/upload-artifact@v4
    #  with:
    #    name: TestingTraders
    #    path: ./publish

    #- uses: actions/download-artifact@v4
    #  with:
    #    name: TestingTraders
    #    path: Zipfiles

    - name: Publishing Artifact
      uses: garygrossgarten/github-action-scp@release
      with:
        local: Zipfiles
        remote: C:\Projects\ContaboApp
        host: ${{ secrets.SERVER_IP }}
        username: ${{secrets.SSH_USER}}
        privateKey: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        rmRemote: true
        
    #- name: Deleting Published Artifact
    #  uses: garygrossgarten/github-action-ssh@0.7.0
    #  with:
    #    command: tar xvf C:\Projects\ContaboApp\Contabo.tar -C C:\Projects\ContaboApp && del /f C:\Projects\ContaboApp\Contabo.tar
    #    host: ${{ secrets.SERVER_IP }}
    #    username: ${{secrets.SSH_USER}}
    #    privateKey: ${{ secrets.PRIVATE_KEY }}
    #    passphrase: ${{ secrets.PASSPHRASE }}
      
````
