### ISSUE TITLE
No longer uploading files

### ISSUE THREAD

**Issue by RSNFreud** [garygrossgarten/github-action-scp#51]
Since the latest change, uploading files doesnt seem to work. It deletes them fine but doesnt upload.

```
name: build site
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:

  build_site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - name: Use cache
      uses: actions/cache@v4
      with:
        # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    - name: build site
      run: npm run build
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: out
        remote: site
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        concurrency: 5
        rmRemote: true

```

**Comment by BernardTeske** [comment]
I have a similar problem: I am using version 0.6.0 in a project. Some files are uploaded, then it takes a long time until the connection times out. The last time it worked was four months ago. Maybe it's due to a change on GitHub? Because I am not using the latest version.

**Comment by RSNFreud** [comment]
![image](https://github.com/user-attachments/assets/1d748ecc-5ad9-4a43-9273-62ece5c501c9)
For reference it seems the files are uploaded as temporary files now and never copied fully

**Comment by RSNFreud** [comment]
https://github.com/garygrossgarten/github-action-scp/issues/50#issuecomment-2222883601

Just confirming that running it on `windows-latest` works so its something with linux

**Comment by luojiyin1987** [comment]
get the same issue, run on `ubuntu-latest`,  becase [new openssh fix](https://blog.qualys.com/vulnerabilities-threat-research/2024/07/01/regresshion-remote-unauthenticated-code-execution-vulnerability-in-openssh-server) ? 

I use other [other scp github action](https://github.com/appleboy/scp-action) to solved. 

https://github.com/kaiyuanshe/OSS-toolbox/pull/16

**Comment by fooying** [comment]
Me too

**Comment by rutvik106** [comment]
Same here. What is the FIX?

**Comment by msveshnikov** [comment]
Doesn't work randomly, ruined my production :( Copies only ~20 files of React app then silently quits. I tried all versions, from 0.5.3 to 0.9

**Comment by roos-robert** [comment]
The only stable "fix" for this is to (sadly) migrate to another action, like this one [https://github.com/appleboy/scp-action](url)

I've done it for all workflows now and everything working great again.

**Comment by Deepika1095** [comment]
Same error I am getting, when I try [other scp github action](https://github.com/appleboy/scp-action) it worked but copy my war file as directory

**Comment by luojiyin1987** [comment]
> Same error I am getting, when I try [other scp github action](https://github.com/appleboy/scp-action) it worked but copy my war file as directory我遇到同样的错误，当我尝试其他 scp github 操作时，它起作用了，但将我的 war 文件复制为目录

```yaml
      - name: Transport Image
        uses: appleboy/scp-action@v0.1.7
        with:
          source: ./build/*.*
          target: /tmp/${{ env.BOX_NAME }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          strip_components: 1
```
you need set  `strip_components` , and set `source: ./build/*.*`
